apiVersion: v1
kind: Service
metadata:
  name: notes
  labels:
    app: notes
spec:
  type: ClusterIP
  selector:
    app: notes
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
